### ISSUE TITLE
"bad magic number" error

### ISSUE THREAD

**Issue by rwhetten** [alguoo314/JASPER#1]
I installed Jellyfish v2.3.0 with the python binding in my home directory on a compute cluster - there are python directories for v2.7, v3.7 and v3.8, and jellyfish.py  was installed in the python2.7/site-packages directory. Running jasper.sh with the options ` -k 25 -t 32 -p 4 -v -d` produces a mer_counts.jf database, but polishing fails with the error message
`Traceback (most recent call last):
  File "$SCRIPTPATH/jasper-1.0.0/bin/jasper.py", line 8, in <module>
    import dna_jellyfish as jf
ImportError: bad magic number in 'dna_jellyfish': b'\x03\xf3\r\n'
`
Is this error related to the fact that jellyfish.py is bound to python2.7 rather than python3.8? If so, how should configuration of Jellyfish compiling be done to ensure installation of jellyfish.py in python3.8/site-packages?

**Comment by rwhetten** [comment]
Update: I used an explicit path to the desired python site-packages directory along with `--enable-swig` option as described in [Jellyfish Issue #38](https://github.com/gmarcais/Jellyfish/issues/38):
`./configure --prefix=$HOME/.local --enable-python-binding=$HOME/.local/lib/python3.8/site-packages --enable-swig`
This is now running; time will tell if that fixed the problem.

**Comment by alguoo314** [comment]
Yes I believe that the bad magic number error is due to the version of python in the binding. Python 3 is needed for the Jellyfish module to work. Glad to hear that the program is running right now. Let me know if you have encountered any other issues.

**Comment by rwhetten** [comment]
The job completed successfully, so apparently the binding to python3.8 worked to correct the problem. I'll close the issue as resolved.
