### ISSUE TITLE
No module named '_dna_jellyfish'

### ISSUE THREAD

**Issue by splaisan** [alguoo314/JASPER#10]
Hi,

As I cannot install software systemwide, I run this in a conda env with biopython installed (Python 3.9.12)
I installed jellyfish (2.3.0) from source with the option '--enable-python-binding' and added its bin folder to my $PATH
my install path is: `/opt/biotools/jellyfish` which contains: `bin, include, share, lib` (in which I have /python3.9/site-packages/ containing `jellyfish.py` and a sub-folder `dna_jellyfish`)

I ran `export PYTHONPATH=/opt/biotools/jellyfish/lib/python3.9/site-packages`

```
$ ll $PYTHONPATH
total 16K
drwxr-xr-x 3  4.0K Nov 15 11:13 .
drwxr-xr-x 3  4.0K Nov 15 10:15 ..
drwxr-xr-x 2  4.0K Nov 15 10:15 dna_jellyfish
-rwxr-xr-x 1   366 Nov 15 10:15 jellyfish.py
```

I also installed Jasper (1.0.3 but reporting 1.0.2 with -h!!) from source in `/opt/biotools/jasper` and added its bin folder to my $PATH

then I ran `jasper.sh --reads ../reads/SRR22216322.fastq.gz -a ../flye_asm_ont/assembly.fasta -k 24 -t 48 -p 4 1>jasper.out 2>&1`

It created the fasta splits and kmers then died while not finding dna_jellyfish

How can I make this dna_jellyfish resource visible to jasper.sh?

Thanks

```
cat jasper.err 
Traceback (most recent call last):
  File "swig/python/dna_jellyfish.py", line 20, in swig_import_helper
  File "/opt/miniconda3/envs/biopython/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_dna_jellyfish'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/biotools/bin/jasper.py", line 10, in <module>
    import dna_jellyfish as jf
  File "swig/python/dna_jellyfish.py", line 23, in <module>
  File "swig/python/dna_jellyfish.py", line 22, in swig_import_helper
  File "/opt/miniconda3/envs/biopython/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_dna_jellyfish'
```

**Comment by splaisan** [comment]
I finally made it with info from https://github.com/gmarcais/Jellyfish/issues/161

I created a jellyfish conda env in which I installed jellyfish (no kidding?) but also biopython and swig then built from source with extra arguments as in the link and finally got it to work. 

Note: I believe I set the prefix to $CONDA_PREFIX for the swig install in order to get the python libraries added to my conda env rather than elsewhere.

I do not dare to present a recipe here as I tried too many things to know what helped really.

One needs strong motivation to use JASPER in order to complete the right install.
good luck with it!

**Comment by alguoo314** [comment]
Hi Stephane.

Thank you for the effort to making the installation work. We have released an integrative version that automatically installs Jellyfish and the bindings: https://github.com/alekseyzimin/JASPER_release/releases 

Did you use the integrative version when you encountered the problem?

Best,
Alina

**Comment by splaisan** [comment]
Hi Alina, no it was all using source.
I now have a working version made from source thanks to other issue comments about the same error.
Thanks

**Comment by splaisan** [comment]
for info I attach here a working conda env that brought jellyfish v2 to life for me. I then installed Jasper from source as discussed above.

````
name: jellyfish2
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.81=py39hd1e30aa_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - kmer-jellyfish=2.3.0=h9f5acd7_3
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=19_linux64_openblas
  - libcblas=3.9.0=19_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libgomp=13.2.0=h807b86a_3
  - liblapack=3.9.0=19_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libsqlite=3.44.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.3=h5eee18b_3
  - numpy=1.22.3=py39hc58783e_2
  - openssl=3.1.4=hd590300_0
  - pcre2=10.40=hc3806b6_0
  - pip=22.1.2=py39h06a4308_0
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=4_cp39
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py39h06a4308_0
  - sqlite=3.39.0=h5082296_0
  - swig=4.1.1=he155508_1
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - dna-jellyfish==0.0.1
prefix: /opt/miniconda3/envs/jellyfish2
```
