### ISSUE TITLE
Which command line is necessary to generate ./configure ?

### ISSUE THREAD

**Issue by kiufta** [alguoo314/JASPER#2]
The release tarball contains a `configure`, but the git master just a `configure.ac`. I've tried to run
```
	autoupdate
	autoconf
```
to generate it, but that wasn't enough:

```
configure.ac:42: warning: AC_OUTPUT should be used without arguments.
configure.ac:42: You should run autoupdate.
configure.ac:6: error: possibly undefined macro: AM_SILENT_RULES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AM_INIT_AUTOMAKE
```

**Comment by alekseyzimin** [comment]
You must have cloned the development tree if you did not have ./configure;  if you do that, you need to run "autoreconf -fi" to initialize the auto-tools.

The preferred way to download and install JASPER is to download the tarball from the release page https://github.com/alguoo314/jasper/releases/download/v1.0.0/jasper-1.0.0.tar.gz , unzip/untar with tar xvf and run ./configure.
