### ISSUE TITLE
JASPER crashes - Module Not Found

### ISSUE THREAD

**Issue by cement-head** [alguoo314/JASPER#3]
Got this error with JASPER:

```
Traceback (most recent call last):
  File "swig/python/dna_jellyfish.py", line 20, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_dna_jellyfish'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cbfgws6/Programs/jasper/jasper-1.0.1/bin/jasper.py", line 8, in <module>
    import dna_jellyfish as jf
  File "swig/python/dna_jellyfish.py", line 23, in <module>
  File "swig/python/dna_jellyfish.py", line 22, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_dna_jellyfish
```

Jellyfish was installed with:

`./configure --enable-python-binding=/usr/lib/python3.6/site-packages --enable-swig`

These lines were added to my bashrc:

`
# Jasper
export PATH=$PATH:$HOME/Programs/jasper/jasper-1.0.1/bin/
export PYTHONPATH=/usr/lib/python3.6/site-packages/
`

Looks as if _dna_jellyfish is here:

![image](https://user-images.githubusercontent.com/1056700/199747647-c9387116-edad-4180-ad95-ce756baed52b.png)

**Comment by alekseyzimin** [comment]
Can you try re-installing jellyfish passing --prefix for the installation directory (without it, jellyfish will be installed into /usr/local/) and not specifying the path for the python binding:

`./configure --enable-python-binding --prefix=$HOME`

and then the binding (jellyfish.py) will be installed in 

`$HOME/lib/python3.6/site-packages`

the binding should look like this (we have python 3.8):

$ ls /ccb/sw/lib/python3.8/site-packages/
dna_jellyfish  jellyfish.py  __pycache__
$ ls /ccb/sw/lib/python3.8/site-packages/dna_jellyfish/
_dna_jellyfish.a  _dna_jellyfish.la  _dna_jellyfish.so  _dna_jellyfish.so.0  _dna_jellyfish.so.0.0.0  __init__.pyc

**Comment by cement-head** [comment]
okay - will do

**Comment by cement-head** [comment]
This completely doesn't work at all.  I don't understand the installation instructions - at all.

**Comment by alekseyzimin** [comment]
What part are you having trouble with -- installing JASPER or installing jellyfish? Please read this about installing jellyfish. https://github.com/gmarcais/Jellyfish

**Comment by cement-head** [comment]
Nope, that makes it locally bound to python 2.7.  This software simply is WAYYYY TOO cumbersome to even install.

**Comment by alekseyzimin** [comment]
you can switch your system to use python 3

**Comment by alekseyzimin** [comment]
here are some instructions, easily found by a google search
https://tecadmin.net/how-to-switch-python-version-in-ubuntu-debian/

**Comment by cement-head** [comment]
Okay, I'll try one more time - but this is ridiculous.  I'm not a coder, but I am experienced with Linux.  This is very, very difficult to install.  You might consider putting this into a CONDA environment - those are simple and easy to use, and do not rely on root permissions, and enable users to install on HPC systems, and/or without conflicting global installs.

**Comment by cement-head** [comment]
Okay, using these instructions: https://tecadmin.net/how-to-switch-python-version-in-ubuntu-debian/
I'm able to get this installed.  PYTHON and JAVA are both a PIA for this kind of installations.  Anyway, it seems to be working now; fingers crossed!

**Comment by cement-head** [comment]
The error persists:

```
Traceback (most recent call last):
  File "swig/python/dna_jellyfish.py", line 20, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_dna_jellyfish'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cbfgws6/Programs/jasper/jasper-1.0.2/bin/jasper.py", line 10, in <module>
    import dna_jellyfish as jf
  File "swig/python/dna_jellyfish.py", line 23, in <module>
  File "swig/python/dna_jellyfish.py", line 22, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_dna_jellyfish'
```

$ python -V
Python 3.6.9

So, it's not the version of PYTHON on the machine (although sorting out 2.7, 3.6, 3.7 was a PIA), but rather the fact that JASPER looks to the main PYTHON install in </usr/lib/python3.6> rather than the specified PYTHONPATH in my $HOME directory for importing the modules.  Even though this variable (PYTHONPATH) is specified to point to my $HOME directory in my <.bashrc> file. 

How do I fix this? Is something symlinked incorrectly?  If so, how do I undo that?

**Comment by alekseyzimin** [comment]
As specified in the installation instructions for JASPER, JASPER needs to know where dna_jellyfish python module is. This module is part of the Jellyfish installation.  Jellyfish installation instructions (https://github.com/gmarcais/Jellyfish):

By default, Jellyfish is installed in /usr/local and the bindings are installed in the proper system location. When the --prefix switch is passed, the executable and bindings are installed in the given directory. For example:

you need to cd to where you untarred/unzipped jellyfish source code, then, assuming you want to install jellyfish under $HOME,

./configure --prefix=$HOME --enable-python-binding
make -j 4
make install
This will install the python binding in $HOME/lib/python2.7/site-packages (adjust based on your Python version, yours is 3.6).
...
export PYTHONPATH=$HOME/lib/python2.7/site-packages

The $PYTHONPATH needs to point to a folder containing dna_jellyfish/ folder and jellyfish.py file.

**Comment by alekseyzimin** [comment]
what is the path to your jellyfish installation?

**Comment by cement-head** [comment]
My jellyfish is installed locally here: </home/cbfgws6/lib/python3.6/site-packages/dna_jellyfish>

I've put this in my bashrc:

export PYTHONPATH=$HOME/lib/python3.6/site-packages/

Is it the forward slash at the end? I'll try re-installing again without the slash.

**Comment by alekseyzimin** [comment]
Can you verify that home/cbfgws6/lib/python3.6/site-packages/dna_jellyfish/ contains jellyfish.py and dna_jellyfish folder?

Then try this:

export PYTHONPATH=$HOME/lib/python3.6/site-packages/:$PYTHONPATH

Then JASPER will work fine.  It looks for jellyfish.py and dna_jellyfish under one of the paths in $PYTHONPATH.

**Comment by cement-head** [comment]
Those are in the folder:
![image](https://user-images.githubusercontent.com/1056700/234046738-f8197c8c-6549-4b71-97f6-b183f8414803.png)

Changing/modifying the PYTHONPATH

FROM:

```
# Jasper
export PATH=$PATH:$HOME/Programs/jasper/jasper-1.0.2/bin/
export PYTHONPATH=$HOME/lib/python3.6/site-packages
```

TO: 

```
# Jasper
export PATH=$PATH:$HOME/Programs/jasper/jasper-1.0.2/bin/
export PYTHONPATH=$HOME/lib/python3.6/site-packages/:$PYTHONPATH
```

crashes Jellyfish, doesn't start.

Also

`export PYTHONPATH=$PYTHONPATH:$HOME/lib/python3.6/site-packages/`

crashes Jellyfish

Trying now _without_ the last forward slash.

`export PYTHONPATH=$HOME/lib/python3.6/site-packages`

I do have python3-dev installed.
---------------------
EDIT: Nope, doesn't work either.

**Comment by alekseyzimin** [comment]
This is interesting, I have just tested everything and it works on my system with fresh install of jellyfish.  A reviewer for our paper has no trouble as well.  Please let me know what error you are getting now.  it may not be related to python path, it could be something else.

**Comment by cement-head** [comment]
Crashed again, keeps looking for the _dna_jellyfish and its missing.  But I think I've found the issue:

https://github.com/gmarcais/Jellyfish/issues/134

**Comment by cement-head** [comment]
Okay, I think it's now working.

Here's the solution, or the amendments to your install instructions that worked for me (Ubuntu 18.04 LTS).

(1) Use update-alternatives to select for python3 as the default.

(2) Install SWIG (distro distribution is fine) via SYNAPTIC

(3) Configure & install JELLYFISH using the following commands:

- Navigate to the untarred jellyfish folder
- $ ./configure --enable-python-binding --enable-swig --prefix=$HOME
- Then enter the swig/python folder _within_ the untarred jellyfish folder and build the swig/python modules using:
- python setup.py build
- python setup.py install --prefix=$HOME
- Then, make & make install jellyfish

(4) Download and install JASPER locally, as per your instructions.

(5) Add the following lines to your <.bashrc> file:

```
# Jasper
export PATH=$PATH:$HOME/Programs/jasper/jasper-1.0.2/bin/
export PYTHONPATH=$HOME/lib/python3.6/site-packages
export PKG_CONFIG_PATH=$HOME/Programs/jellyfish/jellyfish-2.3.0
```

**Comment by cement-head** [comment]
@alekseyzimin For some reason, python was not building the swig/python module as per this issue: https://github.com/gmarcais/Jellyfish/issues/134

Building it manually and installing it to <--prefix=$HOME> made it work.  Not really a JASPER issue, but rather a JELLYFISH issue - something must have changed in python3 (??)

**Comment by alekseyzimin** [comment]
Thank you!  This is good to know!  I appreciate your effort in resolving this issue, it will be useful for other users that may encounter this problem!

**Comment by cement-head** [comment]
Yeah, it was strange, eh?  Anyway, I really wanted to get this to work, as I have older CLR data & Illumina short read data, and this polisher looks very promising.

**Comment by alguoo314** [comment]
Thank you for your patience and endeavor to figure this out! And thank you for using JASPER! :)
