### ISSUE TITLE
Installation problems (make install)

### ISSUE THREAD

**Issue by paq88** [alguoo314/JASPER#6]
Hello, I am having trouble installing JASPER software using the installation guide on GitHub. I have already downloaded the latest release (version 1.0.2) and unpacked it using tar. I then attempted to configure it, and when I tried to use 'make install', I encountered the following error:

make[1]: Entering directory '/media/DANE/home/nflow/ms_data/jasper/jasper-1.0.2'
/usr/bin/mkdir -p '/media/DANE/home/nflow/ms_data/jasper/jasper-1.0.2/bin'
/usr/bin/install -c src/jasper.sh src/jasper.py src/jellyfish.py '/media/DANE/home/nflow/ms_data/jasper/jasper-1.0.2/bin'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/media/DANE/home/nflow/ms_data/jasper/jasper-1.0.2'

I have searched online for a solution and found that I should contact the script author for help. As I am comparing different genome assembly techniques for my diploma, I would really appreciate your assistance in getting JASPER installed. Thank you in advance for your response.

Marek

**Comment by cement-head** [comment]
That's not an error; that is expected behaviour. There is no "ERROR" message in the terminal output.

Why do you think that there is an error?
