### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by chunmn826** [alguoo314/JASPER#8]
Hi, I am trying to use JASPER to polish a flye assembly. To do so I used the following command.

/sw/eb/sw/JASPER/1.0.2-foss-2022a/bin/jasper.py -a /scratch/user/chunmn26/P2_results/flye_assemblies/A222210626/assembly.fasta -r '/scratch/user/chunmn26/P2_resuls
/QC/processed/A222210626.fastq'

However when I do this I get the following error.

/home/chunmn26/.local/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release 
of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
Traceback (most recent call last):
  File "/sw/eb/sw/JASPER/1.0.2-foss-2022a/bin/jasper.py", line 10, in <module>
    import dna_jellyfish as jf
ModuleNotFoundError: No module named 'dna_jellyfish'

Please let me know how I can fix this issue.

**Comment by alguoo314** [comment]
Hi, 

It seems that it cannot find Jellyfish. Could you refer to the README and check if Jellyfish was installed and the Python binding was successful?

**Comment by chunmn826** [comment]
Hi I am using JASPER from the module library.

Max Chung B.S.
***@***.***
(920) 757-4227
MS Student | Department of Veterinary Pathobiology
Texas A&M University, Veterinary Education Research and Outreach
3201 Russell Long Blvd, Canyon, TX 79015

**Comment by alekseyzimin** [comment]
Hi, we generally recommend that you install JASPER from the release that we provide on github, following installation instructions provided, both for jellyfish and JASPER.  In your case the problem is that Jellyfish python binding is not installed.  Please install Jellyfish python binding following the instructions provided and export the PYTHONPATH variable as instructed.

**Comment by alekseyzimin** [comment]
We are now working on a new comprehensive release of JASPER that will install Jellyfoish automatically and configure the appropriate bindings.  We are planning to get it out in less than 1 week.

**Comment by chunmn826** [comment]
Hi, I have installed Jasper. But I get the following error when I run the following script

conda create --name jasper python=3.8
conda activate jasper
tar -xzf jasper-1.0.2.tar.gz
cd jasper-1.0.2
./configure --prefix=$PWD
make install
cd /scratch/user/chunmn26/Test
PYTHONPATH=/scratch/user/chunmn26/jasper-1.0.2/bin
jasper.sh --assembly /scratch/user/chunmn26/P1_results/flye_assemblies/A222080303/assembly.fasta --reads "/scratch/user/chunmn26/P1_results/QC/processed/A222080303.fastq" -k 25 -t 16 -p 4

Error:

[Wed Sep 27 14:23:57 CDT 2023] Using BATCH SIZE 267079
[Wed Sep 27 14:23:57 CDT 2023] Using existing jellyfish database mer_counts25.jf
[Wed Sep 27 14:23:57 CDT 2023] Polishing
[Wed Sep 27 14:23:57 CDT 2023] Lower threshold for unreliable kmers is 13
[Wed Sep 27 14:23:58 CDT 2023] Polishing failed

In the jasper.err output: I get this error.

Traceback (most recent call last):
File "/sw/eb/sw/JASPER/1.0.2-foss-2022a/bin/jasper.py", line 8, in
from Bio import pairwise2
ModuleNotFoundError: No module named 'Bio'

**Comment by alguoo314** [comment]
Did "pip3 install biopython" solve the issue?
